---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - community.devops.org.pt
  resources:
  - devopsnapraia
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - community.devops.org.pt
  resources:
  - devopsnapraia/finalizers
  verbs:
  - update
- apiGroups:
  - community.devops.org.pt
  resources:
  - devopsnapraia/status
  verbs:
  - get
  - patch
  - update
